INSERT INTO CIDADE(ESTADO, NOME) VALUES('SC', 'Chapecó');
INSERT INTO CIDADE(ESTADO, NOME) VALUES('PR', 'Curitiba');
INSERT INTO CIDADE(ESTADO, NOME) VALUES('SC', 'Irati');
INSERT INTO CIDADE(ESTADO, NOME) VALUES('SC', 'Pinhalzinho');
INSERT INTO CIDADE(ESTADO, NOME) VALUES('SP', 'São Paulo');

INSERT INTO CLIENTE(IDADE, NOME, SEXO, CIDADE_ID) VALUES( 22, 'Bruno', 'Masculino', 1);
INSERT INTO CLIENTE(IDADE, NOME, SEXO, CIDADE_ID) VALUES( 18, 'Axel', 'Masculino', 2);
INSERT INTO CLIENTE(IDADE, NOME, SEXO, CIDADE_ID) VALUES( 18, 'Carla', 'Feminino', 1);